# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip }:

linkFarm "zig-packages" [
  {
    name = "12205353c7f550b1aadf245d70a30d5a0a92eb151f735e15358ff35fcfe53343c93f";
    path = fetchzip {
      url = "https://github.com/kython28/jdz_allocator/archive/refs/tags/0.0.4.zip";
      hash = "sha256-OY+WyMRk/VWpPrSlBORxzdOGjd64aliU3e41j08rxJI=";
    };
  }
]
